/**
 * Post-render remediation for the Listbox component.
 *
 * Fixes attempted:
 * - Add role="button" and aria-haspopup="listbox" to .listbox-trigger
 * - Add aria-expanded to the trigger reflecting open/closed state
 * - Add aria-controls linking the trigger to .listbox-dropdown
 * - Add role="listbox" to .listbox-dropdown
 * - Add role="option" and aria-selected to each .listbox-option
 * - Add aria-activedescendant on the trigger/listbox for the focused option
 * - Add Up/Down arrow key navigation and Home/End between options
 * - Add Escape to close the listbox and return focus to the trigger
 * - Add Enter/Space to select the focused option
 * - Associate visible label (.listbox-label-text) with the listbox
 *
 * Limitations discovered:
 * - React controls open/close state; Escape and selection keystrokes attempt
 *   to trigger a click on the trigger/option, but rely on the component's own
 *   event handlers responding correctly to synthetic events
 * - aria-activedescendant requires the listbox to have a stable DOM ID on each
 *   option; IDs are generated by this fix and may change across re-renders
 * - The trigger element must receive focus before the listbox opens; focus
 *   management after selection returns to the trigger via programmatic focus
 */

import { setRole, setAria, setTabIndex, ensureId, labelledBy, controls } from '../lib/aria.js';
import { buttonify, onKeyDown } from '../lib/keyboard.js';
import { queryAll } from '../lib/dom.js';
import { createFix } from '../lib/fixFactory.js';

function isOpen(dropdown) {
  if (!dropdown) return false;
  return !dropdown.hidden && window.getComputedStyle(dropdown).display !== 'none';
}

function remediateListbox(widget) {
  const trigger = widget.querySelector('.listbox-trigger');
  const dropdown = widget.querySelector('.listbox-dropdown');
  const labelText = widget.querySelector('.listbox-label-text');
  const options = queryAll('.listbox-option', widget);

  if (trigger) {
    buttonify(trigger, 'listbox-trigger');
    setAria(trigger, 'haspopup', 'listbox');
    setAria(trigger, 'expanded', String(isOpen(dropdown)));

    if (dropdown) {
      controls(trigger, dropdown);
    }

    if (labelText) {
      labelledBy(trigger, labelText);
    }
  }

  if (dropdown) {
    setRole(dropdown, 'listbox');
    ensureId(dropdown, 'listbox-dropdown');

    if (labelText) {
      labelledBy(dropdown, labelText);
    }
  }

  options.forEach((option, i) => {
    setRole(option, 'option');
    ensureId(option, `listbox-option-${i}`);
    setTabIndex(option, -1);
    const isSelected = option.classList.contains('selected') ||
      option.getAttribute('aria-selected') === 'true';
    setAria(option, 'selected', String(isSelected));
  });

  // Keyboard navigation within dropdown
  if (dropdown) {
    onKeyDown(dropdown, 'listboxArrowNav', (e) => {
      const opts = queryAll('.listbox-option', dropdown);
      if (opts.length === 0) return;

      const current = document.activeElement;
      const idx = opts.indexOf(current);

      let next = idx;

      switch (e.key) {
        case 'ArrowDown':
          e.preventDefault();
          next = Math.min(idx + 1, opts.length - 1);
          if (idx === -1) next = 0;
          break;
        case 'ArrowUp':
          e.preventDefault();
          next = Math.max(idx - 1, 0);
          break;
        case 'Home':
          e.preventDefault();
          next = 0;
          break;
        case 'End':
          e.preventDefault();
          next = opts.length - 1;
          break;
        case 'Enter':
        case ' ':
          e.preventDefault();
          if (current && opts.includes(current)) {
            current.click();
          }
          if (trigger) trigger.focus();
          return;
        case 'Escape':
          e.preventDefault();
          if (trigger) {
            trigger.click();
            trigger.focus();
          }
          return;
        default:
          return;
      }

      if (next !== idx) {
        opts[next].focus();
        if (dropdown) {
          setAria(dropdown, 'activedescendant', opts[next].id);
        }
      }
    });

    // Open listbox: focus first option
    onKeyDown(trigger || dropdown, 'listboxOpenNav', (e) => {
      if (e.key === 'ArrowDown' && isOpen(dropdown)) {
        e.preventDefault();
        const opts = queryAll('.listbox-option', dropdown);
        if (opts.length > 0) opts[0].focus();
      }
    });
  }
}

export const apply = createFix('.listbox-widget', remediateListbox);
